"$schema" = 'https://starship.rs/config-schema.json'

[directory]
truncation_symbol = '.../'
fish_style_pwd_dir_length = 1

[shell]
disabled = false

[status]
disabled = false

[sudo]
disabled = false

[os]
disabled = false

[time]
disabled = false
time_format = '%TT%z %Y-%m-%d'
