[programs.windows]
# Install with winget so values are ids
universal = [
  'Nushell.Nushell',
  'Git.Git',
  'JesseDuffield.lazygit',
  'Starship.Starship',
  'Neovim.Neovim',
  'junegunn.fzf',
  'rjpcomputing.luaforwindows',
]
gui = ['Neovide.Neovide', 'wez.wezterm']
node = ['CoreyButler.NVMforWindows']
python = ['PyPA.Hatch']

[programs.other]
# Install with homebrew
universal = [
  'bat',
  'bat-extras',
  'eza',
  'fzf',
  'neovim',
  'nushell',
  'starship',
  'zellij',
]
node = ['node-build']
python = ['hatch']
